### ISSUE TITLE
 when I breakdown the furnace, it just gives cobbled deepslate and not for cobblestone

### ISSUE THREAD

**Issue by PTOM76** [Pitan76/UncraftingTable#1]
Reporter: SapFireLynx ([Report](https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric?comment=48))

**Comment by Ayutac** [comment]
Furnace can be crafted from any combination of cobblestone and cobbled deepslate. It is impossible to know what was used to craft it. A default must be set and this might be cobblestone instead of cobbled deepslate but it is not atm.

**Comment by PTOM76** [comment]
support item tags
