### ISSUE TITLE
Uncrafting into UU matter is... unfortunate

### ISSUE THREAD

**Issue by Ayutac** [Pitan76/UncraftingTable#10]
Hi there,

in TechReborn there is this nifty item called UU matter and you can craft an awful lot of things from it. It's kinda a cure-for-all. That said for the small price of 8 diamonds to obtain your table, we can uncraft simple stone into UU matter and use that matter to craft diamond ore, resulting in easy infinite everything.

I would propose disabling the uncrafting into UU matter, or make it configurable at least, because it can easily unbalance modpacks with no easy way of rebalancing atm afaik. If you agree, I will help you implement this, since I'm a TechReborn Dev and I have a pretty good idea of how to achieve this.

**Comment by PTOM76** [comment]
Proposed Thank you.
Added config to enable/disable Uncrafting of UU-Matter.
