### ISSUE TITLE
World crash when clicking arrows to change recipe

### ISSUE THREAD

**Issue by The-Forge-Master** [Pitan76/UncraftingTable#13]
To reproduce:

- Place item into bench.
- Click an arrow to change the output.
- World crashes.

Connection Lost 
Internal Exception: java.lang.NoSuchMethodError: 'net.minecraft.world.inventory.Slot
ml.pkom.uncraftingtable.UncraftingScreenHandler.getSlot(int)'

Found in singleplayer, unsure of behavior in multiplayer.

Crash occurred in modified TNP Limitless 6 modpack, running Minecraft 1.19.2, mod version 1.1.6, Forge version 43.2.0, OpenJDK 17.0.3+7. Adding MCPitanLibarch version 1.2.8 did not help.

**Comment by PTOM76** [comment]
Fixed
https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch/files/4249547
https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric/files/4249586
