### ISSUE TITLE
(1.19.4 FORGE) - Ver. 1.2.3 Crashes Xaero's Worldmap

### ISSUE THREAD

**Issue by Tursiops-G** [Pitan76/UncraftingTable#24]
Crash at startup. Reverting to ver. 1.2.0 works normally.
(Forge Only - Fabric ver. 1.2.3 doesn't crash)
[Uncrafting Table Crash.txt](https://github.com/Pitan76/UncraftingTable/files/11012330/Uncrafting.Table.Crash.txt)

**Comment by PTOM76** [comment]
There was an error in the build classes, so I deleted the entire build directory and rebuilt.
