### ISSUE TITLE
Uncrafting table breaks enchantments

### ISSUE THREAD

**Issue by Gamemassa** [Pitan76/UncraftingTable#4]
MC Version: 1.19.2
Loader: Fabric (Latest version)
Mod Version: 1.1.0

Uncrafting an enchanted item with a book in the left slot successfully moves all enchantments to the book, but renders the book unusable. In the first two screenshots below, I'm using a Protection III book I bought from a villager, and it's letting me enchant the chestplate. But in the next two below those, I'm using an Unbreaking III book that I got from uncrafting an item that had Unbreaking III, and the game is not letting me enchant the chestplate (in fact the anvil doesn't even appear to be registering the book).

![2022-10-23_11 42 28](https://user-images.githubusercontent.com/18667108/197401810-e6045e98-d57d-4703-961f-7981a8b3ec85.png)

![2022-10-23_11 42 20](https://user-images.githubusercontent.com/18667108/197401740-470be666-f716-4b90-bc2f-cf8841b8a5f2.png)

![2022-10-23_11 42 37](https://user-images.githubusercontent.com/18667108/197401917-33662023-977a-4d19-bddb-c9ecfb47bb62.png)

![2022-10-23_11 40 58](https://user-images.githubusercontent.com/18667108/197401935-a2e640a1-74ae-43be-9085-19c10c69cba1.png)

**Comment by PTOM76** [comment]
Uploaded v1.1.1.
It should have been fixed.
Thank you for your report.

**Comment by Gamemassa** [comment]
I can confirm, the issue is definitely fixed with version 1.1.1
Thank you for looking into it.
