### ISSUE TITLE
Crashes on right click with the new MCPitanLib v1.7.9 forge

### ISSUE THREAD

**Issue by DTech10** [Pitan76/UncraftingTable#43]
[Latest Logs](https://mclo.gs/4z5LGw6)
[Crash Log](https://mclo.gs/LHwMzyh)

[Video](https://youtu.be/4Q8FRJsaLzo)

**Comment by TheCyaniteProject** [comment]
For anyone else reading this, it works with MCPitanLib v1.7.8 for me. I'm playing Fabric 0.14.23

**Comment by DTech10** [comment]
Tested the new version, it's now fixed
