### ISSUE TITLE
Uncrafting Table crashes on rightclick 1.20.1 Fabric

### ISSUE THREAD

**Issue by ZombieKeks** [Pitan76/UncraftingTable#45]
https://pastebin.com/xY5TAqGx

**Comment by Tursiops-G** [comment]
It's mcpitanlibarch 1.7.9 that's broken. :(
Downgrade mcpitanlibarch to version 1.7.8 and see if that helps.

**Comment by ZombieKeks** [comment]
Im using version 1.6.8-1.20.1 :) works great!

**Comment by ZombieKeks** [comment]
Sadly the update did not fixed it

https://pastebin.com/X2tLnkTX

**Comment by ZombieKeks** [comment]
Thanks for fixing. Appreciate you!
