### ISSUE TITLE
Uncrafting Table crashing 1.20.1 Fabric

### ISSUE THREAD

**Issue by bons66** [Pitan76/UncraftingTable#46]
MC 1.20.1 + Fabric 0.14.24

Mods:

> architectury-9.1.12-fabric.jar
> cloth-config-11.1.106-fabric.jar
> fabric-api-0.90.7+1.20.1.jar
> RoughlyEnoughItems-12.0.674.jar
> mcpitanlibarch-1.8.1-1.20.1-fabric.jar
> UncraftingTable-fabric-1.2.8.jar

Crash when click on UncraftingTable interface buttons. 
![BSOD](https://github.com/Pitan76/UncraftingTable/assets/98187937/24437eb7-d05a-41c8-9ac5-17ee48b3a039)

Versions -

> mcpitanlibarch-1.7.8-1.20.1-fabric.jar
> UncraftingTable-fabric-1.2.6.jar

- everything OK

Crash report
[crash-2023-11-08_15.04.47-client.txt](https://github.com/Pitan76/UncraftingTable/files/13296532/crash-2023-11-08_15.04.47-client.txt)

**Comment by bons66** [comment]
mcpitanlibarch-1.8.2-1.20.1-fabric.jar
UncraftingTable-fabric-1.2.8.jar

Same issue.

**Comment by DTech10** [comment]
mcpitanlibarch-1.8.2-1.19.2-forge
UncraftingTable-forge-1.2.8

same for me
[Latest Log](https://mclo.gs/C5A7nMl)
[Crash Report](https://mclo.gs/WtNqBvM)

**Comment by bons66** [comment]
mcpitanlibarch-1.8.3-1.20.1-fabric
UncraftingTable-fabric-1.2.8

Same issue.

**Comment by festro** [comment]
Does the same on forge
UncraftingTable-forge-1.2.8
mcpitanlibarch-1.8.2-1.20.1-forge

[latest.log](https://github.com/Pitan76/UncraftingTable/files/13468534/latest.log)
[crash-2023-11-26_16.17.47-client.txt](https://github.com/Pitan76/UncraftingTable/files/13468535/crash-2023-11-26_16.17.47-client.txt)

**Comment by bons66** [comment]
mcpitanlibarch-1.8.4-1.20.1-fabric
UncraftingTable-fabric-1.2.8

Same issue.

**Comment by DemifiendCruithne** [comment]
i am having the same issue on forge playing minecraft version 1.19.2:

forge 43.3.0
architectury-6.5.85-forge
mcpitanlibarch-1.8.3-1.19.2-forge
UncraftingTable-forge-1.2.8

the full crash report is here:
[crash-2023-11-28_18.53.53-client.txt](https://github.com/Pitan76/UncraftingTable/files/13491968/crash-2023-11-28_18.53.53-client.txt)

`java.lang.NoSuchMethodError: 'net.minecraft.network.FriendlyByteBuf net.minecraft.network.FriendlyByteBuf.m_130079_(net.minecraft.nbt.Tag)'
	at ml.pkom.uncraftingtable.UncraftingScreen.lambda$initOverride$1(UncraftingScreen.java:75) ~[UncraftingTable-forge-1.2.8.jar%23146!/:?] {re:classloading}`
is the significant part for me

given it's showing up on both forge and fabric under the same circumstances i think it's reasonable to include it here for context / further data

**Comment by bons66** [comment]
New version - OK

MC 1.20.1 + Fabric 0.14.24

UncraftingTable-fabric-1.2.9
mcpitanlibarch-1.8.4-1.20.1-fabric
fabric-api-0.91.0+1.20.1
architectury-9.1.12-fabric
cloth-config-11.1.106-fabric

... and other >350 mods ...

**Comment by DTech10** [comment]
mcpitanlibarch-1.8.4-1.19.2-forge
UncraftingTable-forge-1.2.9

all good, this can closed now

**Comment by PTOM76** [comment]
thank you for your reporting!
