### ISSUE TITLE
Crash when Cycling Thru Recipies [Forge 1.20.1]

### ISSUE THREAD

**Issue by Aetrnl94** [Pitan76/UncraftingTable#48]
When using the Uncrafting table while in Forge 1.20.1 - Mod Version 1.2.8, I had an item in the table, and when I clicked on the arrows to cycle through the other recipes that were possible, the game crashed to desktop and gave the following error message:

The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'net.minecraft.network.FriendlyByteBuf net.minecraft.network.FriendlyByteBuf.m_130079_(net.minecraft.nbt.Tag)'

[latest.log](https://github.com/Pitan76/UncraftingTable/files/13470171/latest.log)
[crash-2023-11-26_23.41.17-client.txt](https://github.com/Pitan76/UncraftingTable/files/13470172/crash-2023-11-26_23.41.17-client.txt)

**Comment by Tursiops-G** [comment]
Use the Uncrafting Table 1.2.6 / MCPitanLib 1.7.8 combination until the 1.2.8 version gets fixed.
