### ISSUE TITLE
[1.18.2] Client CTD on a Server with vUncraftingTable-forge-1.1.0.jar

### ISSUE THREAD

**Issue by MokahTGS** [Pitan76/UncraftingTable#5]
Getting a client crash to desktop when trying to use the Uncrafting Table from version UncraftingTable-forge-1.1.0.jar.

Crash Log: https://pastebin.com/i8N9Zfaa

Forge Version: 40.1.84

Modpack: Cosmic Magitech - https://www.curseforge.com/minecraft/modpacks/cosmic-magitech

**Comment by PTOM76** [comment]
Uploaded v1.1.1.
It should have been fixed.
Thank you for your report.
