### ISSUE TITLE
Table not able to be mined faster with appropriate tool

### ISSUE THREAD

**Issue by GoldenFurredFox** [Pitan76/UncraftingTable#52]
When you use any tool, the table always breaks just as slow as it would with your hand (or slower in some cases depending on the item and where/if you're standing).

You'd expect an axe and/or a pickaxe to break it faster, but neither does.

Please implement a fix.

**Comment by PTOM76** [comment]
Fixed, thank you

**Comment by GoldenFurredFox** [comment]
1.3.4 for Fabric on Minecraft 1.19.2 lacks the necessary minecraft:mineable tags.
