### ISSUE TITLE
Table deletes items under your cursor when you uncraft if your inventory is full and also deletes items if you quick move an item into the table when it's part of the result of something already in there

### ISSUE THREAD

**Issue by GoldenFurredFox** [Pitan76/UncraftingTable#53]
![javaw_j2WDc2ifCL](https://github.com/Pitan76/UncraftingTable/assets/28793227/ceaa2f0b-d239-4d30-8edd-d48e21d4d315)
![javaw_kLYSoxLiD8](https://github.com/Pitan76/UncraftingTable/assets/28793227/7d355101-f286-47c9-b8f2-0ce67af9b480)

**Comment by PTOM76** [comment]
Thanks for your reporting
