### ISSUE TITLE
UncraftingTable-forge-1.2.6 needs MCPitanLibarch-1.5.5 or above but MCPitanLibarch is not on curseforge

### ISSUE THREAD

**Issue by raziel23x** [Pitan76/UncraftingTable#58]
to be able to use the mod in a 1.20.1 modpack it needs to have the MCPitanLibarch 
 lib installed and it is not on curseforge only MCPitanLib but i found it on https://modrinth.com/mod/mcpitanlibarch/

**Comment by PTOM76** [comment]
https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch
