### ISSUE TITLE
[Bug]: Duplication

### ISSUE THREAD

**Issue by Anonyku05** [Pitan76/UncraftingTable#63]
As said in the title, basically there is a glitch/bug that allows to get the receipe of the items without uncrafting it, making infinite ressources, check the video below (1.20.4 fabric, mod version 1.3.4)

https://github.com/Pitan76/UncraftingTable/assets/48128391/d3fa592f-7965-4885-b829-bd239e903774

**Comment by javk-adaw** [comment]
Version 1.20.2 also has this problem

**Comment by PTOM76** [comment]
Thank you for your reporting.
It was fixed
